model_train_type = "sdxl-lora"
pretrained_model_name_or_path = "H:/sd-webui-aki-v4.2/models/Stable-diffusion/sd_xl_base_1.0_0.9vae_2.safetensors"
v2 = false
train_data_dir = "F:/AI/lora-scripts-gui/train/hone"
prior_loss_weight = 1
resolution = "1024,1024"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1_024
bucket_reso_steps = 32
output_name = "xd-home"
output_dir = "./output"
save_model_as = "safetensors"
save_precision = "bf16"
save_every_n_epochs = 2
max_train_epochs = 10
train_batch_size = 1
gradient_checkpointing = true
network_train_unet_only = true
network_train_text_encoder_only = false
learning_rate = 0.0002
unet_lr = 0.0002
text_encoder_lr = 0.00002
lr_scheduler = "constant"
lr_warmup_steps = 0
optimizer_type = "AdaFactor"
network_module = "networks.lora"
network_dim = 64
network_alpha = 64
network_dropout = 0
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = false
weighted_captions = false
keep_tokens = 0
max_token_length = 255
seed = 1_337
clip_skip = 2
mixed_precision = "bf16"
full_fp16 = false
full_bf16 = false
xformers = true
lowram = false
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
persistent_data_loader_workers = true
multi_gpu = false
